global userNameList
global newUserNameList
newUserNameList = []


def UserName():
    global userNameList
    userNameStr = input("Input Your Name or \"QUIT\":")
    userNameStr = userNameStr.upper() #capitalize all enteries.
    if userNameStr == "QUIT":
        exit()
    else:
        userNameStr = userNameStr.replace(" ", "") #remove any whitespace from userNameStr
        userNameList = list(userNameStr) #convert userNameStr to a list, witch each character being a different item. 
        return userNameList


def CompareNameToDict():
    global dictList
    global userNameList
    global newUserNameList
    dictList = ["AARTUK", "AASIMAR", "AASIMAR", "ABALLIN", "ABEIL", "ABHIR", "ABOLETH", "ABRIAN", "ACHERI", "ACHUNGA",
                "ACIDBLOB", "ACIDBORN", "ACROPHID", "ACTAEON", "ADAPTOR", "ADARO", "ADDAZAHR", "ADHERER", "ADUJA",
                "AELFBORN", "AFANC", "AGARAT", "AGNATH", "AGTA", "AHMORAS", "AHUIZOTL", "AIRFISH", "AIRJELLY",
                "AKETHETI", "AKIKAGE", "AKLEU", "ALJAHAR", "ALMIRAJ", "ALAGHI", "ALAN", "ALARON", "ALBARI", "ALCOR",
                "ALEAX", "ALGOID", "ALGROTH", "ALGUDUIR", "ALLIP", "ALLURA", "ALPACA", "ALPHAKS", "AMAKUA", "AMBIENT",
                "AMBITION", "AMISKWIA", "AMITOK", "AMMUT", "AMOBEA", "AMOEBA", "AMORPH", "AMYRIA", "ANADJIIN", "ANAGO",
                "ANAK", "ANAKORE", "ANCESTOR", "ANCIENT", "ANDELOID", "ANDROID", "ANEMONE", "ANGEL", "ANGREDEN",
                "ANGRYMOB", "ANHANGA", "ANIMAL", "ANIMATOR", "ANIMUS", "ANKHEG", "ANKOU", "ANNELID", "ANT", "ANTLION",
                "ANTELOPE", "ANTLOID", "ANTMAN", "ANUBI", "ANUCHU", "AOA", "APE", "APEP", "APOLLYON", "APRIG", "ARANEA",
                "ARANEA", "ARATHA", "ARBOREAN", "ARBORROR", "ARCHON", "ARGAS", "ARGOS", "ARMAND", "ARMMEGH", "ARRACCAT",
                "ARUCHA", "ASABI", "ASAG", "ASHCHILD", "ASHWITCH", "ASHALAN", "ASHEN", "ASHERATI", "ASHGAUNT",
                "ASHIERA", "ASHIRA", "ASHURA", "ASHWORM", "ASPECT", "ASPERI", "ASPIS", "ASRAI", "ASTRAL", "ASURA",
                "ASWANG", "ATHACH", "ATONAL", "AURATUS", "AUROCH", "AUSTRICH", "AUTUMN", "AVANC", "AVANGION", "AVARI",
                "AVERX", "AVIARAG", "AVILDAR", "AVLEDOR", "AVOLAKIA", "AWNSHEGH", "AXANI", "AXEBEAK", "AZER", "AZOUL",
                "AZURIN"
                "BKRATH", "BROHG", "BAATUN", "BATRAA", "BAAK", "BAAZRAG", "BABAYAGA", "BABBLER", "BABOON", "BACAR",
                "BACCHAE", "BADGER", "BAJANG", "BAKEMONO", "BAKENEKO", "BAKKAS", "BAKU", "BALAENA", "BALHIIR", "BALROG",
                "BANEDEAD", "BANSHEE", "BANSHRAE", "BANTH", "BARGDA", "BARGHEST", "BARIAUR", "BARIC", "BARKBURR",
                "BARROWE", "BASILISK", "BASS", "BASSNIP", "BAT", "BATDEMON", "BATFLY", "BATIBAT", "BAUHYIN", "BEAR",
                "BEAR", "BEASTFLY", "BEAVER", "BEE", "BEETLE", "BEGUILER", "BEHEMOTH", "BEHIR", "BEHOLDER", "BEHOLDER",
                "BEKKAH", "BELABRA", "BELGOI", "BELIARH", "BELKER", "BETRAYER", "BETTA", "BHUKA", "BHUT", "BINOU",
                "BICHIR", "BICLOPS", "BIONOID", "BIRD", "BISAN", "BISON", "BLAZON", "BLIGHT", "BLIZZARD", "BLOODED",
                "BLOODROT", "BLOODSAC", "BLUE", "BOAR", "BODACH", "BODAK", "BOGBEAST", "BOGHOUND", "BOGIMP", "BOGWADER",
                "BOGEYMAN", "BOGGART", "BOGGLE", "BOGLE", "BOGUN", "BOGY", "BOLANDI", "BOLNEWT", "BONACON", "BONE",
                "BONEOOZE", "BONECLAW", "BONECLAW", "BONELEAF", "BONELESS", "BONETREE", "BONEWORM", "BONEYARD",
                "BONYHAND", "BOOBRIE", "BOOKA", "BOOKWORM", "BOOWRAY", "BOUNDER", "BOWLER", "BOWLYN", "BRAGGER",
                "BRAMBLE", "BRANTA", "BRASSMAN", "BRAXAT", "BRIARVEX", "BROWNIE", "BRUJA", "BRUTE", "BRUTEMAN",
                "BRYLUKA", "BUBBLE", "BUCKAWN", "BUGRIDER", "BUGBEAR", "BUGDEAD", "BULETTE", "BULL", "BULLYWUG",
                "BUNYIP", "BUOMMAN", "BURAQ", "BURBUR", "BUSEN", "BUSO", "BUTU", "BUZZARD", "BUZZBUG", "BVANEN",
                "BYAKHEE", "BZASTRA",
                "CACOPS", "CACTACAE", "CACTUS", "CAECILIA", "CAIRN", "CAIVEH", "CALIENTO", "CALOPUS", "CAMEL", "CANARY",
                "CANSIN", "CANTOR", "CAPYBARA", "CARACDIR", "CARAPACE", "CARAXE", "CARCASS", "CARIBOU", "CARP", "CARRU",
                "CASURUA", "CAT", "CATFISH", "CATFOLK", "CATTLE", "CAVELING", "CAVVEKAN", "CAYMA", "CAYPR", "CELADRIN",
                "CENTAUR", "CENTER", "CERBERUS", "CETUS", "CHAC", "CHAGMAT", "CHAK", "CHAKCHAK", "CHAMROL", "CHANDOS",
                "CHANEQUE", "CHANTH", "CHAOND", "CHATTUR", "CHATURAN", "CHEETAH", "CHEKRYAN", "CHEPEKWE", "CHETZEDE",
                "CHEVALL", "CHINOONI", "CHICKEN", "CHIMAERA", "CHIMER", "CHIMERA", "CHIMERIC", "CHIPMUNK", "CHITINE",
                "CHOKER", "CHOKER", "CHRAAL", "CHTHON", "CHUU", "CHULCRIX", "CHUN", "CHUUL", "CHUUL", "CIFAL", "CILOPS",
                "CINCIUT", "CIPACTLI", "CIVET", "CLAKAR", "CLAM", "CLAPODEE", "CLAPPER", "CLERIC", "CLIMBDOG",
                "CLOAKER", "CLOUDRAY", "CLUBNEK", "COGGLE", "COLFEL", "COLOSSUS", "COLTPIXY", "CONTINH", "CORAL",
                "CORANACH", "CORKIE", "COROLLAX", "CORPSE", "COUATL", "COUATL", "COUERL", "COUGAR", "COW", "COYAANI",
                "COYOTE", "CRAB", "CRAMESHA", "CRANE", "CRAYFISH", "CREEPER", "CRESTCAT", "CRICKET", "CRIMSON",
                "CRODLU", "CROW", "CRUCIAN", "CRUSTAID", "CRYION", "CRYSMAL", "CUROTAI", "CURST", "CURUPIRA",
                "CUTEDROP", "CWNANNWN", "CYBORG", "CYCLOPS", "CYNOPARD",
                "DHINNI", "DABUS", "DAELKYR", "DAGGORAN", "DAGORRAN", "DAHAK", "DAHDI", "DAHRRAIN", "DAKON", "DALMOSH",
                "DARK", "DARKLORD", "DARKONES", "DARKTREE", "DARKWING", "DARKHAWK", "DARKHOOD", "DARKLING", "DARKLORE",
                "DARKSNAP", "DARKWING", "DARN", "DARQUE", "DARTER", "DEAGLU", "DEATH", "DEATHDOG", "DEATHFEY",
                "DEATHOX", "DEBBI", "DECAPUS", "DEEPMOLD", "DEEPONE", "DEEPONES", "DEEPLING", "DEER", "DEFACER",
                "DEFILED", "DEITY", "DEKAYI", "DELMAIN", "DELPHON", "DELSMAR", "DELVER", "DEMARAX", "DEMODAND", "DEMON",
                "DENIZEN", "DEODAND", "DERYNI", "DESMODU", "DEVA", "DEVETE", "DEVIL", "DEVILDOG", "DEVOURER",
                "DEWFROND", "DHAMPIR", "DHAOT", "DHEVSAHR", "DHOLE", "DHOUR", "DIABOLO", "DIABOLUS", "DIAKK", "DIGER",
                "DIGESTER", "DINGO", "DINGONEK", "DINOSAUR", "DIOPSID", "DIREHELM", "DISCORD", "DISIR", "DIURGE",
                "DIZANTAR", "DOBIE", "DOCCUOC", "DOCENTI", "DOG", "DOGAI", "DOHWAR", "DOKON", "DOKUFU", "DOLGAUNT",
                "DOLGHAST", "DOLGRIM", "DOLGRIM", "DOLGRUE", "DOLPHIN", "DOMOVOI", "DONKEY", "DOOMED", "DOOMSEPT",
                "DOOR", "DORVESH", "DOVE", "DOWAGU", "DRACON", "DRACONES", "DRACONIC", "DRAEDEN", "DRAENEI", "DRAGGER",
                "DRAGITE", "DRAGON", "DRAGON", "DRAGONET", "DRAGONNE", "DRAKE", "DRAKEN", "DRAKNOR", "DRAY", "DREAD",
                "DREADRAM", "DREGOTH", "DRELB", "DRIDER", "DRIFTER", "DRIK", "DROLL", "DROMITE", "DROWNED", "DROWNER",
                "DRYAD", "DUCK", "DUNECRAB", "DUROCIB", "DUSANU", "DUSKER", "DUSKLING", "DUSTFORM", "DUSTGULL", "DVATI",
                "DWARF", "DYLL",
                "EAGLE", "EATENONE", "EBLIS", "ECHIDNA", "ECHO", "ECHYAN", "EEAAR", "EEL", "EFFIGY", "EGARUS",
                "EHRSHEGH", "EIDOLON", "EKIMMU", "EKRAT", "ELADRIN", "ELAN", "ELEMENT", "ELENOIN", "ELEPHANT", "ELF",
                "ELGHONN", "ELGONN", "ELHORIAD", "ELK", "ELMARIN", "EMPATHOS", "EMPIPATH", "EMRE", "EMU", "ENDUK",
                "ENEKO", "ENERGON", "ENGINE", "ENSLAVER", "ENTOMBED", "ENTOMBER", "ENTROPE", "ENTROPIC", "EPHEMERA",
                "EQUAR", "EQUICEPH", "EQUUS", "ERDLAND", "ERDLU", "ERLAND", "ERMINE", "ERYOPS", "ESSARCH", "ESTHETIC",
                "ETHER", "ETHYK", "ETTERCAP", "ETTIN", "EXARCH", "EXECUTED", "EYE", "EYEWEED", "EYEWING",
                "FACET", "FACHAN", "FAEDORNE", "FAEL", "FAENARE", "FAERIE", "FAINIL", "FAIRY", "FALLEN", "FAMILIAR",
                "FANGGEN", "FARISEE", "FAUN", "FAZE", "FEARWEED", "FEARWOOD", "FEASTER", "FEEDER", "FEESU", "FELGUARD",
                "FELLHAWK", "FELLJAW", "FENETTE", "FENHOUND", "FENSIR", "FERAL", "FERRET", "FETCH", "FETISH", "FEYRI",
                "FEYBORN", "FEYLAAR", "FEYSTAG", "FEYWING", "FHORGE", "FIEND", "FIENDISH", "FIGHTER", "FIGMENT",
                "FIGONA", "FIGURINE", "FIHYR", "FIRBOLG", "FIREBIRD", "FIREFLY", "FIRELICH", "FIRENEWT", "FIRESTAR",
                "FIRETAIL", "FIREWEED", "FIRVULAG", "FISH", "FLAILER", "FLAPSAIL", "FLARD", "FLAWDER", "FLICKER",
                "FLITTE", "FLOATER", "FLOLITE", "FLUMPH", "FLY", "FLYMAN", "FOCOID", "FOLUGUB", "FOMORIAN", "FORLARR",
                "FORMIAN", "FORSAKEN", "FOULWING", "FOX", "FRAAL", "FRACTINE", "FRELN", "FREMLIN", "FROG", "FROGFOLK",
                "FROGFOLK", "FROST", "FUDOSHI", "FUNGAL", "FUNGOID", "FUNGUS", "FUNNO", "FURBOLG", "FURIES", "FYREFLY",
                "FYRSNACA",
                "GGROKON", "GADABOUT", "GAHONGA", "GAJ", "GAJUSIAN", "GAKARAK", "GAKI", "GALADUR", "GALLTRIT",
                "GALUMPH", "GAMBADO", "GAMBOL", "GAME", "GANDAYAH", "GAR", "GARBLER", "GARBUG", "GARGOYLE", "GARM",
                "GARMORM", "GARN", "GARUDA", "GASPAR", "GATHRA", "GAUND", "GAUNT", "GAUNT", "GAUTIERE", "GAZER",
                "GEBBETH", "GECKO", "GEIST", "GELJILL", "GELUN", "GEMVAR", "GEN", "GENASI", "GENIE", "GENOCID",
                "GEONID", "GERAN", "GERBIL", "GERIVAR", "GETIET", "GHAST", "GHASTLY", "GHAYROG", "GHAZNETH", "GHL",
                "GHOST", "GHOST", "GHOUL", "GHOUL", "GHOULISH", "GHRALTHI", "GHRIEST", "GHUL", "GHUUNA", "GIANT",
                "GIFF", "GIRAFFE", "GIRALLON", "GITH", "GITHILID", "GKLOKLOK", "GLAISTIG", "GLAMER", "GLITCH",
                "GLOAMING", "GLOMUS", "GLOOM", "GLOURA", "GLUEY", "GNASHER", "GNAWBUG", "GNOAT", "GNOLL", "GNOLL",
                "GNOME", "GOAT", "GOATMAN", "GOBLIN", "GOBLYN", "GOLDBUG", "GOLDFIN", "GOLEM", "GOLIATH", "GOLMOID",
                "GONDSMAN", "GONN", "GOOM", "GOOSE", "GOPHER", "GORAK", "GORGON", "GORSE", "GORYNYCH", "GORYO",
                "GOSSAMER", "GRAHLUK", "GRANGERI", "GRAV", "GRAVORG", "GRAYMOLD", "GRAYOOZE", "GRAZER", "GREATORM",
                "GREELOX", "GRELL", "GRELL", "GREMKIN", "GREMLIN", "GRENDEL", "GREYMAN", "GRICK", "GRIDBUG", "GRIFFON",
                "GRIFFON", "GRIGAUR", "GRILLING", "GRIM", "GRIMLOCK", "GRIMOR", "GRIMP", "GRIPPLI", "GRISGOL", "GROMIT",
                "GROMMAM", "GRONK", "GROUPER", "GROWLER", "GRUE", "GRUNG", "GRUWAAR", "GRYPH", "GRYPHON", "GRYTHOK",
                "GUARMORI", "GUARDIAN", "GULGAR", "GULLION", "GULPER", "GUNTHOSH", "GURAAH", "GURGOTCH", "GURRASH",
                "GWILLION", "GWYLLION", "GYERIAN", "GYRE",
                "HCALOS", "HAPONY", "HADOZEE", "HAG", "HAGSPAWN", "HAINU", "HAIRIYO", "HALBERD", "HALFELF", "HALFFEY",
                "HALFOGRE", "HALFORC", "HALFLING", "HAMA", "HAMAGUAN", "HAMSTER", "HAND", "HANEMURI", "HANNYA",
                "HARAEVOR", "HARE", "HARNAQ", "HARPY", "HARRIAT", "HARRIER", "HARRLA", "HARROW", "HARSSAF", "HATORI",
                "HATRED", "HAUDHLA", "HAUN", "HAUNDAR", "HAUNT", "HAVOCORB", "HAWK", "HAZARD", "HEDGEHOG", "HEJKIN",
                "HELBORN", "HELGOST", "HELIAN", "HELLBRED", "HELOT", "HENDAR", "HENRE", "HEREX", "HETFISH", "HGAUN",
                "HIDDEN", "HIVENEST", "HJORT", "HOARDER", "HOBYAH", "HOLBAG", "HOLLOW", "HORAG", "HORAST", "HORAX",
                "HORDE", "HORDLING", "HORG", "HORGAR", "HORLA", "HORNET", "HORSE", "HOUND", "HOUOU", "HOWLER", "HSIAO",
                "HUHSIEN", "HUECUVA", "HUITZIL", "HULDER", "HULLOCK", "HUMAN", "HUMBABA", "HUNEFER", "HUNTSMAN",
                "HUPTZEEN", "HURGEON", "HURRUM", "HUSKLESS", "HUTAAKAN", "HYAKUHEI", "HYBSIL", "HYDDEN", "HYDRA",
                "HYDRAKIN", "HYENA", "HYLEM", "HZUTZU",
                "IBEM", "IBIS", "IBIXIAN", "IBIXIAN", "ICEBEAST", "ICEHOUND", "ICEWORM", "ICEGAUNT", "ICELING",
                "ICETAIL", "IDFIEND", "IGUANA", "IHAGNIM", "IKIRYO", "ILLURIEN", "IMAGO", "IMBUL", "IMMORTAL", "IMMOTH",
                "IMORPH", "IMP", "INCUBUS", "INFECTED", "INFERNAL", "INGOGO", "INGUNDI", "INIX", "INSECT", "INVADER",
                "IORAMH", "IRDATREE", "IRONMAN", "IRONPIG", "IRONMAW", "ITCHIES", "IVYIX",
                "JACKAL", "JADEFISH", "JAEBRIN", "JAGENDAR", "JAGRE", "JAGUAR", "JAHI", "JAKAR", "JAKOB", "JANKX",
                "JANKZ", "JARBO", "JARKUNG", "JAWG", "JHAKAR", "JOR", "JORRI", "JOZHAL", "JUHRION", "JUJUBEE", "JUMPER",
                "KRRR", "KA", "KAURSA", "KADA", "KAIJU", "KAIL", "KALMURU", "KALA", "KALANU", "KALIJ", "KALIN",
                "KALMARI", "KALUK", "KAMADAN", "KAMATLAN", "KAMPFULT", "KANGAROO", "KANIDOLL", "KANK", "KANSEN",
                "KAORTI", "KAPPA", "KARAKARA", "KARSITE", "KARTANG", "KARTOEBA", "KATANGA", "KECH", "KEEPER", "KELMAIN",
                "KELPIE", "KENDER", "KENKU", "KER", "KERCPA", "KHAASTA", "KHARGRA", "KHEPRI", "KIRIN", "KILLOREN",
                "KINDORI", "KIP", "KIRLANAN", "KIRREN", "KIREKAN", "KIRRE", "KITSU", "KITSUNE", "KIVIT", "KIZOKU",
                "KLAATAH", "KLAR", "KLUZD", "KLYNDES", "KNA", "KNARLED", "KNIGHT", "KOALA", "KOBOLD", "KODRAGON",
                "KOPRU", "KORINTH", "KORMUS", "KORRED", "KRAG", "KRAGLING", "KRAJEN", "KRAKEN", "KREEL", "KRENSHAR",
                "KRINTH", "KROLLI", "KROTTER", "KROWK", "KRUEL", "KRUTHIK", "KSAST", "KUEI", "KUMO", "KUOTOA", "KUPUK",
                "KURACK", "KURGE", "KUSNAR", "KYRA", "KYRIE", "KYRYN", "KYSETH", "KYTHON", "KZIN", "KZINTI",
                "LADYVOL", "LAIKA", "LAKSHU", "LAMIA", "LAMMASU", "LAMPREY", "LANDWYRM", "LAPIDAN", "LAPUTAN",
                "LARAKEN", "LARIDIAN", "LARVA", "LASHENZA", "LASHWEED", "LASK", "LASTTREE", "LAUREN", "LAVAFISH",
                "LAVAOOZE", "LAVAWORM", "LEECH", "LEOMARH", "LEOPARD", "LESHAY", "LESHII", "LESHY", "LESKYLOR",
                "LESSER", "LEVELLER", "LHEE", "LHOSK", "LICE", "LICH", "LICHKING", "LICHLING", "LILLEND", "LINDWORM",
                "LINNORM", "LINQUA", "LION", "LIRR", "LITH", "LIZARD", "LLAMA", "LLORT", "LOA", "LOCATHAH", "LOCHNAR",
                "LOCULI", "LOCUST", "LOMENDUR", "LOSEL", "LOST", "LOSTBOY", "LOSTSOUL", "LOXO", "LUMI", "LUNAMOTH",
                "LUPASUS", "LUPIN", "LURKER", "LUTUM", "LYBARRDE", "LYBBARDE", "LYNX", "LYTHLYX",
                "MAYUAN", "MAANVAKI", "MADBORN", "MAELUTH", "MAENAD", "MAGEBANE", "MAGEDOOM", "MAGEN", "MAGERA",
                "MAGGOT", "MAGISTAR", "MAGISTER", "MAGMIN", "MAGMITE", "MAGORI", "MAGPIE", "MAGRAN", "MAHR", "MAJALOR",
                "MALASTOR", "MALFERA", "MALGOREN", "MALUSITE", "MAMONO", "MANDRAKE", "MANGGUS", "MANIKIN", "MANNI",
                "MANOTAUR", "MANTA", "MANTARI", "MANTRAP", "MAPMAKER", "MARA", "MART", "MARGAY", "MARIKITH", "MARKEEN",
                "MARL", "MARMOSET", "MARODIN", "MARQUIN", "MARRASH", "MARRELLA", "MARSALAI", "MARTIAN", "MARUT",
                "MARZANNA", "MASGAI", "MASHER", "MASKHI", "MASTODON", "MAUG", "MAULGOTH", "MAURID", "MEAZEL",
                "MEDIATOR", "MEDUA", "MEDUSA", "MEENLOCK", "MEGALITH", "MEK", "MEKILLOT", "MEME", "MEMEDI", "MEMELITH",
                "MEMNINE", "MENSHEN", "MEORTY", "MEPHIT", "MEPHLING", "MERCANE", "MERFOLK", "MERHORSE", "MERKHANT",
                "MERLING", "MIGO", "MICEMAN", "MICROBE", "MIHSTU", "MILLIKAN", "MIMBLE", "MIMIC", "MINDWORM",
                "MINDLORD", "MINDWEB", "MINIKANK", "MINIDRAG", "MINIMAL", "MINK", "MINOTAUR", "MIRRORED", "MISI",
                "MIST", "MISTLING", "MITE", "MIVILORN", "MLARRAUN", "MOANBIRD", "MOB", "MODRON", "MOHRG", "MOIGNO",
                "MOLDMAN", "MOLDWYRM", "MOLE", "MONITOR", "MONKEY", "MONOLISK", "MONOLITH", "MOONDOG", "MOONMAN",
                "MOONCALF", "MOONRAT", "MOORMAN", "MOOSE", "MORBE", "MORDAGZ", "MORDRIN", "MORG", "MORGHISS", "MORIN",
                "MORKOTH", "MOROPUS", "MORTAI", "MORTANAX", "MORTISS", "MOSASAUR", "MOSQUITO", "MOSS", "MOSSLORD",
                "MOTH", "MOTHER", "MOTHMAN", "MOURNER", "MOUSE", "MUSPORE", "MUDFIEND", "MUDMAN", "MUDMAW", "MUJINA",
                "MUL", "MULCHER", "MULE", "MULWORM", "MUMIA", "MUMMY", "MURGUL", "MURDAKUS", "MURK", "MURKHERD",
                "MURLOC", "MURSKA", "MURYAN", "MUSKOX", "MWELLRET", "MYCONID", "MYYRRHN",
                "NARUK", "NAGA", "NAGATHA", "NAGPA", "NAMECH", "NANDIE", "NAREK", "NARRA", "NASNAS", "NAT", "NATHRI",
                "NAUTILUS", "NAYCHURR", "NAZGUL", "NDENGEI", "NECK", "NECROTON", "NEOGI", "NERAPHIM", "NEREID", "NERRA",
                "NERUBIAN", "NESHEZU", "NETHER", "NETHLING", "NEWT", "NEZUMI", "NIIATH", "NICEPONA", "NIFERN", "NIKA",
                "NIKAAL", "NIKTOO", "NIKUMIZU", "NILBOG", "NILSHAI", "NIMBUS", "NING", "NINGYO", "NIPPER", "NISHRUU",
                "NISSIE", "NOCNITSA", "NOCTRAL", "NOGRA", "NONAFEL", "NORAN", "NORKER", "NORNS", "NOTHIC", "NOTION",
                "NUE", "NUKARUMI", "NUNDA", "NYCTER", "NYMPH", "NYMPH", "NYTH", "NZEFULOI",
                "OCABER", "OBATI", "OAKBRUTE", "OARD", "OBAKE", "OBEDIENT", "OBLIVIAX", "OCELOT", "OCHIMO", "OCKN",
                "OCTOPIN", "OCTOPUS", "OCULARON", "OCULON", "ODEM", "ODOPI", "OGRE", "OGRE", "OGRESLUG", "OGRILLON",
                "OGRIMA", "OHDOWAS", "OHDOWA", "OKAPI", "OLDONES", "OLIPHANT", "OMMWA", "OMSHIRIM", "ONAGER", "ONCO",
                "ONI", "ONILORD", "ONIKAGE", "ONISU", "ONYXWORM", "OONAI", "OORTLING", "OOWAH", "OPABINIA", "OPHIDIAN",
                "OPINICUS", "OPOSSUM", "ORACLE", "ORC", "ORCWORT", "OREAD", "ORGAUTHA", "ORGLASH", "ORLYTHYS", "ORMYRR",
                "OROCHI", "ORPSU", "ORUNLU", "OSCRAY", "OSQUIP", "OSTRICH", "OTTER", "OTTOIA", "OTYUGH", "OVERLORD",
                "OVERSEER", "OVERWORM", "OWL", "OWLBEAR", "OWLMAY", "OX", "OYSTER",
                "POH", "PAHARI", "PAIN", "PAKA", "PALADIN", "PANDAREN", "PANTHER", "PARAGON", "PARASITE", "PARDAL",
                "PARPARIT", "PEACOCK", "PECH", "PEDIPALP", "PEGASUS", "PEGATAUR", "PEKKLE", "PELGRANE", "PELICAN",
                "PELIN", "PELTAST", "PELUDA", "PENGUIN", "PER", "PERNICON", "PERYTON", "PEST", "PETAL", "PHAERIMM",
                "PHAETHON", "PHALAGAR", "PHANATON", "PHANE", "PHANT", "PHANTASM", "PHANTOM", "PHARGION", "PHASM",
                "PHEASANT", "PHIRBLAS", "PHIUHL", "PHOENIX", "PHOOKA", "PHOUKA", "PHRENIC", "PHTHISIC", "PHUNG",
                "PHYGORAX", "PHYNXKIN", "PIERCER", "PIG", "PIGALOPE", "PIGEON", "PIKE", "PIRANHA", "PITLORD",
                "PLANTMAN", "PLASM", "PLASMAN", "PLASMOID", "PLATYPUS", "PODLING", "POLECAT", "POLYMAR", "POLYP",
                "PONY", "POOKA", "PORPHYR", "PORPOISE", "PORTON", "POWER", "PRESENCE", "PRIMAL", "PRISMFLY", "PRODUCER",
                "PROWLER", "PSIMULE", "PSITAN", "PSURLON", "PTERRAN", "PTERRAX", "PUDDING", "PUFFER", "PUMA", "PUPPET",
                "PYREWYRM", "PYREEN", "PYROLISK",
                "QNIDAR", "QLIPPOTH", "QOTHE", "QUAGGOTH", "QUAGMIRE", "QUANLOS", "QUATSCH", "QUAZAC", "QUELL",
                "QUELZARN", "QUESAR", "QUETZL", "QUEVARI", "QUEZZER", "QUILBOAR", "QUILL", "QUIPPER", "QULLAN",
                "QUORBRED", "QUORI",
                "RAAIG", "RAAKLE", "RAAM", "RAAVASTA", "RABBIT", "RABBIUN", "RACCOON", "RADIANT", "RAEL", "RAGER",
                "RAGEWIND", "RAGEWING", "RAGNORRA", "RAIMENT", "RAKASTA", "RAKNAKLE", "RAKSHASA", "RALKAN", "RAM",
                "RAMADEEN", "RAMFISH", "RAMPAGER", "RAMPHOR", "RANDARA", "RANGER", "RAPPER", "RAPTOR", "RAPTORAN",
                "RASCLINN", "RAST", "RAT", "RATATOSK", "RATFOLK", "RATLING", "RAUCUX", "RAUTYM", "RAVEN", "RAVENKIN",
                "RAVENOUS", "RAVER", "RAVID", "RAY", "RAYFISH", "RAZHAK", "RAZOREEL", "REAVE", "REAVER", "REDSTORM",
                "REDWIDOW", "REDCAP", "REEKMURK", "REGGELID", "REIGAR", "REINDEER", "REJKAR", "REKEIHS", "REL",
                "RELIQUS", "REMADE", "REMNANT", "REMORHAZ", "RENDER", "RENK", "REPEATER", "RESIDENT", "RESIDENT",
                "REVENANT", "REVENER", "REVILER", "RHEA", "RHEK", "RHINO", "RHULTAKH", "RILKAN", "RILMANI", "RINGWORM",
                "RIPPER", "ROBOT", "ROC", "ROCKMAN", "ROCKWYRM", "ROCKFANG", "ROCKFISH", "ROGUE", "ROHCH", "ROKOR",
                "ROM", "ROPER", "ROTGRUB", "ROTH", "ROVER", "RUINWYRM", "RUKANYR", "RUKTOI", "RULT", "RUMMELE",
                "RUSALKA", "RUVE", "RUVOKA", "RVKCHL", "RYLKAR",
                "SABULORD", "SACAANTI", "SACI", "SACROL", "SADHUIN", "SAHUAGIN", "SAINT", "SAKINA", "SALMON",
                "SANDFOLK", "SANDWORM", "SANDSTAR", "SANDLING", "SANDMAN", "SANDWORM", "SARAPH", "SARKRITH", "SARRUKH",
                "SARTANI", "SARU", "SASHALUS", "SATYR", "SAUGH", "SAURIAL", "SAVAGE", "SCALADAR", "SCAMILLE", "SCAPE",
                "SCATHE", "SCAVVER", "SCAVYT", "SCORNED", "SCORPION", "SCORROW", "SCOURGED", "SCRAB", "SCRYXULL",
                "SCYLLAN", "SEABONZE", "SEACAT", "SEACOW", "SEAGULL", "SEALION", "SEAORC", "SEASPAWN", "SEATIGER",
                "SEAWYRM", "SEAHORSE", "SEAL", "SEASTAR", "SEAWOLF", "SEBACEAN", "SEED", "SEEMER", "SEERGAR",
                "SEGARRAN", "SEGBEN", "SELKIE", "SENMURV", "SENTINEL", "SENTRY", "SERPENT", "SERPLAR", "SERRA",
                "SERVAL", "SERVITOR", "SERYULIN", "SESKARRA", "SHAAZ", "SHABOATH", "SHAD", "SHADE", "SHADOVIG",
                "SHADOW", "SHADOWEN", "SHAGGOTH", "SHAGGUN", "SHALARIN", "SHANSAO", "SHARD", "SHARG", "SHARGUGH",
                "SHARJAN", "SHARK", "SHARKKIN", "SHARN", "SHATJAN", "SHAZAK", "SHEDU", "SHEE", "SHEEN", "SHEEP",
                "SHENSHU", "SHIFTER", "SHIKE", "SHIMNUS", "SHIRYO", "SHIVAK", "SHIVHAD", "SHIYOKAI", "SHOCKER",
                "SHOGGOTH", "SHOOSUVA", "SHREEKAH", "SHREW", "SHRIKE", "SHROOM", "SHU", "SHUNNED", "SHYFT", "SIABRIE",
                "SIDHE", "SILAT", "SILATIC", "SILENI", "SILKWYRM", "SILKIE", "SIMURGH", "SIND", "SINKWORM", "SIREN",
                "SIRINE", "SIRRUSH", "SISTHIK", "SISIUTL", "SISLAN", "SITAK", "SITH", "SIV", "SKANDAR", "SKARN",
                "SKELETON", "SKELTAR", "SKELTER", "SKERATH", "SKINKITE", "SKINWING", "SKIRR", "SKIURID", "SKORENOI",
                "SKORPIO", "SKOTOS", "SKRAT", "SKRIAXIT", "SKRIT", "SKULK", "SKULKER", "SKUM", "SKUNK", "SKUZ",
                "SKYLOTUS", "SKYFISH", "SKYKINE", "SKYWYRM", "SKYZORRN", "SLAAD", "SLAPPER", "SLASRATH", "SLAYER",
                "SLAYMATE", "SLEEK", "SLIG", "SLINGER", "SLINKER", "SLOTH", "SLUAGH", "SLUDGE", "SLUG", "SLUK", "SLYTH",
                "SMILODON", "SNAIL", "SNAKE", "SNAKEDOG", "SNOWFURY", "SNYAD", "SOHMIEN", "SOLLUX", "SONGBIRD", "SOO",
                "SORROW", "SOULMASK", "SPANNER", "SPARK", "SPECTER", "SPECTRAL", "SPECTRE", "SPECTRE", "SPHEX",
                "SPHINX", "SPIDER", "SPIDRON", "SPIKER", "SPIRIT", "SPIRRAX", "SPLITTER", "SPOOK", "SPORACLE",
                "SPOREBAT", "SPRACKLE", "SPRIGGAN", "SPRING", "SPRITE", "SPRYJACK", "SQUARK", "SQUEAKER", "SQUEALER",
                "SQUID", "SQUIRREL", "SQUONK", "SRAT", "SSURRAN", "SSVAKLOR", "STAG", "STAGWEED", "STALKER", "STALWART",
                "STAMPEDE", "STARFISH", "STEEDER", "STINGER", "STIRGE", "STITCHED", "STONEARM", "STRIDER", "STRIGLOI",
                "STRINE", "STROAN", "STURGEON", "STWINGER", "STYR", "SUFOLK", "SUMONKEY", "SUCCUBUS", "SUCCULUS",
                "SUGO", "SUISSEEN", "SULL", "SUMMER", "SUNFLY", "SUNWYRM", "SURCHUR", "SURTAKI", "SURVIVOR", "SUSURRUS",
                "SUWYZE", "SWAN", "SWANMAY", "SYGRA", "SYLLIX", "SYLPH", "SYMBIONT", "SYNAD", "SZASSTAM",
                "TCHOWB", "TLIZ", "TNEREC", "TUENRIN", "TABAXI", "TABI", "TAER", "TAER", "TAINTED", "TAKESASU", "TAKIS",
                "TAKO", "TALON", "TAMHI", "TANARUKK", "TANU", "TANUKI", "TAPIR", "TAREK", "TARI", "TARMAK", "TARSIER",
                "TASLOI", "TATALLA", "TAUREN", "TAURIC", "TAUTHAR", "TAYELLAH", "TAYFOLK", "TELTHOR", "TELVAR", "TEMBO",
                "TEMPEST", "TENDRIL", "TENEBRIS", "TENER", "TENGU", "TERLEN", "TERMITE", "TERN", "THAALUD", "THAGDAL",
                "THANOI", "THENDAR", "THOMIL", "THOQQUA", "THORK", "THORN", "THORNY", "THOUL", "THRAX", "THREEP",
                "THRUOCK", "THRUSH", "THUNDER", "TIKHANA", "TIBBIT", "TICK", "TICKLER", "TIEFLING", "TIELFING", "TIGER",
                "TIGERFLY", "TINMAN", "TINKERER", "TIRAPHEG", "TIRBANA", "TIRICHIK", "TITAN", "TITANIC", "TKEL",
                "TLALUSK", "TOAD", "TODAL", "TOEBITER", "TOJANIDA", "TOLWAR", "TOMBMOTE", "TONAL", "TOOL", "TORTLE",
                "TORTOISE", "TOTEM", "TRALUSK", "TRAP", "TRAPPER", "TREANT", "TREE", "TRELON", "TREN", "TRESPER",
                "TRIFFID", "TRILLOCH", "TRIN", "TRIST", "TRITON", "TROGG", "TROLL", "TROLLKIN", "TROSIP", "TROUT",
                "TROW", "TSNNG", "TSO", "TSOCHAR", "TSUNO", "TUBEWORM", "TULK", "TUPAN", "TURKEY", "TURLUNG", "TURSA",
                "TURTLE", "TUSKARR", "TUYEWERA", "TWEEN", "TYBOR", "TYERKOW", "TYLOR", "TYMINID", "TYPO", "TYRG",
                "UBUE", "UBUME", "UDOROOT", "ULDRA", "ULIK", "ULORIAX", "UMBRA", "UMBRAL", "UMBROOD", "UMPLEBY",
                "UNBODIED", "UNBORN", "UNDEAD", "UNICORN", "UNICOW", "UNTHLATU", "URVILE", "UREPONA", "URAGIRI",
                "URCHIN", "URD", "URDARK", "URISK", "URLSHELL", "URSKAN", "URSOI", "USHEMOI", "USUNAG", "UTHRAKI",
                "UTUKKU", "UVUUDAUM",
                "VAATH", "VAATI", "VACUOUS", "VAGABOND", "VALICORN", "VALKYRIE", "VAMPIRE", "VAMPITE", "VAMPYRE",
                "VANARA", "VANISHED", "VARAG", "VARKHA", "VARSK", "VARTHA", "VASHAR", "VEERU", "VEHRTEIG", "VELROC",
                "VENGER", "VENOMDOG", "VERBEEG", "VERINI", "VERME", "VERMILIA", "VERMIN", "VERTIGO", "VERX", "VESERAB",
                "VIAVODE", "VILA", "VILEDOG", "VILES", "VILIRIJ", "VILLICHI", "VILSTRAK", "VILTCH", "VILY", "VIRUS",
                "VISAGE", "VISHAP", "VISION", "VOAT", "VODONI", "VODYANOI", "VOIDOOZE", "VOIDMIND", "VOLODNI", "VOLT",
                "VORLOG", "VORR", "VORTEX", "VOSTARR", "VOUR", "VRIL", "VRILL", "VROON", "VULTURE",
                "WAFF", "WAIVERAS", "WALLABY", "WALLARA", "WALRUS", "WANGCHI", "WARBEAST", "WARI", "WARLOCK", "WARLORD",
                "WASP", "WASTREL", "WATCHER", "WATROACH", "WATTLEY", "WAVEFIRE", "WAYNHIM", "WEASEL", "WEAVER",
                "WEBBIRD", "WEEPER", "WEIRD", "WEMIC", "WENDIGO", "WERERAT", "WEZER", "WHALE", "WHARLYSK", "WHEEP",
                "WHIPPER", "WHIPWEED", "WHIRLER", "WICHTLIN", "WIGGLE", "WIGHT", "WILD", "WILDHUNT", "WILDKIN",
                "WILDREN", "WILORA", "WINDIGO", "WINGED", "WINGWYRD", "WINTER", "WIRCHLER", "WIRRN", "WISP", "WISPLING",
                "WITHERA", "WITHERED", "WIWAXIA", "WIZARD", "WIZSHADE", "WOGEN", "WOHK", "WOLF", "WOLFWERE", "WOLVERN",
                "WOODMAN", "WOODWOAD", "WOODLING", "WOOZLE", "WORGEN", "WORGHEST", "WORM", "WORMLORD", "WRAB", "WRAITH",
                "WRECKER", "WRIGGLY", "WRYBACK", "WUNAMZI", "WURM", "WURMLING", "WYCHGLOW", "WYCHLAMP", "WYNDLASS",
                "WYNZET", "WYRD", "WYRM", "WYRMEN", "WYRMLET", "WYSTE", "WYVERN",
                "XAVER", "XENOA", "XEPH", "XERICHON", "XILL", "XILOB", "XORBEAST", "XORN", "XTABAY", "XVART", "XYTAR",
                "YAGKOSHA", "YAGGOL", "YAHOO", "YAK", "YAKFOLK", "YAKSHA", "YALE", "YALLIX", "YAUMOR", "YAZATA", "YELG",
                "YESHIR", "YESHOM", "YETHAY", "YETI", "YITSAN", "YOHOIA", "YOKAI", "YOREI", "YOWLER", "YPHOZ", "YRTHAK",
                "YUANTI", "YUGOLOTH", "YUKIONNA", "YURIAN",
                "ZTAL", "ZAIRTAIL", "ZAMULBAH", "ZARATAN", "ZARD", "ZARGON", "ZAT", "ZEALOT", "ZEBRA", "ZENYTHRI",
                "ZERN", "ZEUGALAK", "ZEZIR", "ZHACKAL", "ZHEN", "ZINCARLA", "ZODAR", "ZOKUJIN", "ZOMBIE", "ZOMBIRE",
                "ZORBO", "ZOVERI", "ZUTEREN", "ZUNGAR", "ZURCHIN", "ZWERGIND", "ZYERN", "ZYGODACT"]
    userNameTuple = tuple(userNameList) #make an immutable tuple "backup" of original userNameList
    print(userNameTuple)
    for r in range(len(dictList)): #start of anagram loop. Should probably move to its own function. 
        dictListName = list(dictList[r])  #assign [r] item to dictListName
        checkCount = 0 
        anagram = ""
        newUserNameList = list(userNameTuple) #assign userNameTuple to a mutable list.
        for r in range(len(dictListName)): #for each character in the list, do this loop.
            if dictListName[r] in userNameList: # if current letter in monster name is in user name do this next
                character = dictListName[r] #give the variable "character" the proerty of the current character in the monster name
                remChar = (userNameList.index(character))  #get the index of that character from that list
                newUserNameList[remChar] = [] #remove that character from userNameList so it can't be used twice
                checkCount += 1
                anagram += str(character) #append that character to the string for the anagram that will be dispalayer
                if checkCount == len(dictListName): ## if we get a complete anagram do this loop, if not, the program will move on the the next item in dictList
                    # print("True:")
                    print(anagram)

def main():
    UserName()
    CompareNameToDict()

main()